// src/components/SafeAnchor/SafeAnchor.jsx
import VueTypes from 'vue-types';

export default {
  name: 'SafeAnchor',

  props: {
    href: VueTypes.string,
    disabled: VueTypes.bool.def(false),
    role: VueTypes.string,
    tabIndex: VueTypes.oneOfType([VueTypes.number, VueTypes.string]),
    componentClass: VueTypes.oneOfType([VueTypes.string, VueTypes.object]).def(
      'a'
    ),
  },

  render() {
    const Component = this.componentClass;
    let tabIndex = this.tabIndex;

    if (this.disabled) {
      tabIndex = -1;
    }

    return (
      <Component
        href={this.href}
        role={this.role}
        tabIndex={tabIndex}
        onClick={this._onClick}
        {...this.$attrs}
        {...{ on: this.listeners }}
      >
        {this.$slots.default}
      </Component>
    );
  },

  methods: {
    _onClick(event) {
      if (this.disabled || !this.href || this.href.trim() === '#') {
        event.preventDefault();
      }

      if (this.disabled) {
        return event.stopPropagation();
      }

      this.$emit('click', event);
    },
  },
};

// src/components/SafeAnchor/safe-anchor.vue
<template>
  <a
    :href="href"
    :disabled="disabled"
    @click="_onClick"
  >
    <slot/>
  </a>
</template>

<script>
export default {
  props: {
    href: String,
    disabled: Boolean,
  },

  data() {
    return {};
  },

  methods: {
    _onClick(event) {
      if (this.disabled || !this.href || this.href.trim() === '#') {
        event.preventDefault();
      }

      if (!this.disabled) {
        return event.stopPropagation();
      }

      this.$emit('click');
    },
  },
};
</script>
